### PR TITLE
WIP: Add webview, tidy up & simplify the plugin source code, #94

### PR DESCRIPTION
**Pull request by olilarkin**
Hey Steve,

I started this branch to show @d3NNEb how to add a webview properly to the iPlug2 project, however when doing so I realised the NAM plug-in source code has ballooned and become very unwieldy. There are things that can be done much more cleanly in iPlug2.

Unfortunately I don't have time to make very atomic PRs to fix all the problems, but I wondered if you would consider a PR like this, trusting me, without being arrogant, that I know what I am doing :-). I don't have the time to go through lots of Q&A on the PR, but I absolutely know how to make the code for the plug-in part of the project much cleaner and better, and easier for others to contribute to. If I can do this I will feel much happier about fixing the various bits of iPlug2 that are coming up as issues with the rapidly expanding NAM community!

Oli

### CODE REVIEW

**Comment by mikeoliphant** [comment]
@olilarkin - regarding this commit: https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/162/commits/63763bedbdfb8d72da0e1c414e1d248eb8e7d215 - are the project files generated in some way, or is this done manually?

**Comment by olilarkin** [comment]
Unfortunately, at the moment, it's manual, but we have seen cmake support on a branch which I hope to merge soon

**Comment by mikeoliphant** [comment]
Cmake support would be great - right now it requires dev intervention on each platform to add/remove/rename plugin code files.

**Comment by sdatkinson** [comment]
Just checking in since this is a draft. Is it close to ready?

Otherwise I may proceed to merge a few of the other PRs.

**Comment by olilarkin** [comment]
please proceed, i need to redo this PR anyway.

**Comment by sdatkinson** [comment]
Thanks for letting me know.

I may steal some pieces anyways like the formatting :)

**Pull request closed without merging**
