### PR TITLE
Support stereo inputs via summing

### LINKED ISSUE #102: [BUG] Cakewalk (DAW) - Plugin goes silent on stereo tracks
**Describe the bug**
The VST (NAM Loader) stops processing sound and behaves like it is bypassed.
All the UI controls stop responding **EXCEPT** input knob and input meter.

**To Reproduce**
1. Add NAM Loader to an audio track and load a capture.
2. Click the small bypass button next to the plugin in the track's 'FX Rack'.
3. Click the small bypass button next to the plugin again.

**Expected behavior**
NAM Loader should still process sound.
Needless to say this does not happen with any other VST plugin.

**Screenshots**
Cakewalk bypass bug

**Desktop (please complete the following information):**
Windows 10.
0.6.2 VST 3
DAW: Cakewalk by BandLab

### PR DESCRIPTION
**Pull request by sdatkinson**
THIS IS NOT DUAL DSP. (#108)

Adds stereo inputs as an option under `config.h`.

Resolves #102

### CODE REVIEW

**Comment by James-F2** [comment]
If possible, please commit this fix in 0.7.2.

**Comment by jimc4893** [comment]
Yes because we needed summing and not stereo inputs processed independently. looks like im going back to neural dsp.

**Comment by James-F2** [comment]
@jimc4893 

Brother, no professional modeler on the market processes sound like two parallel amp model, Helix, AxeFx III, etc, none.
A stereo input is summed to mono because the model itself is mono, just like a guitar tube amp.
In DAW you want each guitar DI tracks to have it's own track.

**Comment by jimc4893** [comment]
@James-F2 
Brother, check neural dsp and any other modern amp modelling SOFTWARE PLUGIN. they take two inputs so that the amp can be processed on two simultaneous panned guitars. why do you think IRs are all in stereo? why do you think custom IR loaders run in stereo? there are IR plugins like NadIR that are older than most young guitarists nowadays, ALL RUNNING IN STEREO. 

it's so you can bus multiple guitar tracks into a group bus and have one amp control multiple guitars. we have all expressed this in other, now closed threads. 

this project had potential but it's not going to compete with amp sims when some of us who double track everything, are requiring to manage 20 instances of the plugin when the latter stereo setup often reduces that to 5.

**Comment by James-F2** [comment]
>why do you think IRs are all in stereo?

IRs are mono.

>why do you think custom IR loaders run in stereo?

To preserve stereo effects placed before the IR loader.


> it's so you can bus multiple guitar tracks into a group bus and have one amp control multiple guitars.

Absolutely not, this is amateurish.
You can't mix and pan individual guitar tracks.
Call any professional mixing engineer and ask if they want a stereo track with two hard panned DI guitars, they will laugh at you.

Neural DSP still recommends multiple mono instances to get better CPU performance despite having a "Stereo Mode".
https://support.neuraldsp.com/help/stereo-mode

>this project had potential but it's not going to compete with amp sims when some of us who double track everything, are requiring to manage 20 instances of the plugin when the latter stereo setup often reduces that to 5.

Please, you're better than that.

**Comment by sdatkinson** [comment]
> 2023-05-02.00-19-04.mp4
> 
> Observation when comparing this addition to the current release version: There is a 1db output increase in this version when audio is rendered in Reaper... This seems to be happening because if running in Reaper, two input pins are selected by default, and this is causing an increase in input gain. So if this is in the next release, it'll be a breaking change.

Good catch--confirmed the 6dB boost (no model loaded).

I'm going to take the average of the inputs inside a DAW (since we expect it to be collapsing a stereo input to mono there) and do a straight sum (as is currently) in the standalone (because we're just trying to "catch whatever the input's on" there and will probably only be getting signal on one channel at a time).

**Comment by sdatkinson** [comment]
@jimc4893 as the PR states, this isn't meant to resolve the dual mono ticket.

It's a first step to resolve issues surrounding folks with workflows where a stereo signal is being given to NAM and either using the left only is worse than summing, or even worse, the DAW crashes.

There's a fair bit of subtlety in doing dual mono, and the plan is to chip away at it piece by piece without any intermediate step setting the overall experience back. That'll probably look like a series of changes in the following order:
1. This PR
2. Stereo IRs
3. The ability to flip a switch to activate dual mono processing (currently you can think of the plugin as running "mono" in terms of that switch--but at least it can do _something_ with a stereo input).

**Comment by James-F2** [comment]
Now with this PR everything is correct. eeff3c5d208b6e078ab6f9d4b2c37b2a7635aa34.

When working in stereo (2-2) the inputs should be averaged: (L+R)/2 to preserve input gain compared to mono (1-2) operation.
This is because in a stereo track when choosing a mono L or R input the DAW with automatically copy L-to-R or R-to-L, this happens before the FX Rack.
On the Standalone app the user is probably plugging into one physical input, so there's no need to average (/2).

**Comment by zavi-sams** [comment]
This 0.7.3. update doesnt resolve my problem....when i send my two take  guitar track thru  NAM , the output is summed to mono  !!!!.........i must run two NAM`s on the stereo track to preserve the stereo signal !!!.....it will be nice if the next update will have this true stereo flow  option !!!

**Comment by sdatkinson** [comment]
> This 0.7.3. update doesnt resolve my problem....when i send my two take guitar track thru NAM , the output is summed to mono !!!!.........i must run two NAM`s on the stereo track to preserve the stereo signal !!!.....it will be nice if the next update will have this true stereo flow option !!!

FYI the top of the PR calls out related Issues, including what you're asking for.

**Pull request merged**
