### PR TITLE
implementation of Evan Heritages design

### PR DESCRIPTION
**Pull request by fichl**
Evan Heritages design now fully implemented.
Also included d3NNEbs folderBrowser
https://github.com/d3NNEb/NeuralAmpModeler-.git
which has still 1 issue (https://github.com/d3NNEb/NeuralAmpModeler-/issues/1).
Couldnt fix this, just make it work a litter better.
See my comments in NeuralAmpModeler.cpp line 593++

### CODE REVIEW

**Comment by d3NNEb** [comment]
VERY nice!!!!!!!!!

**Comment by d3NNEb** [comment]
@fichl I fixed all issues with the folderBrowser.  can't seem to commit code to your PR, so you'll have to grab my changes and integrate them in your PR.  here:  https://github.com/d3NNEb/NeuralAmpModeler-

also, i noticed that when the filename is long, it obscures the nav arrows, what can we do about this?
Capture

**Comment by fichl** [comment]
@d3NNEb thanks but this didnt fix the issue for the vst plugin...
--> open NAM vst3, select model, select IR, close plugin window and reopen --> arrows on model missing
--> open NAM vst3, select IR, select model, close plugin window and reopen --> arrows on IR missing
--> when opening a saved project in DAW with model and IR set and another NAM instance recently used different paths for model and IR ---> both arrows missing.

You are right about the arrows getting obscured with long filenames.
Design wise i would say that the arrows should stay in a fixed position and the filename gets shortened so it doesnt reach the arrows. 
Either loosing the end of the filename or make the whole filename scroll back and forth is what comes to my mind.
I just cant do that in reasonable time because of lacking skills ;)
What do you think ?

**Comment by d3NNEb** [comment]
> 

@fichl not sure what you are doing differently but it's working for me - i made a video to show proof:
https://youtu.be/TYge2iu78G4

you fetched my repo, or copied the files from the git listing into your solution?

**Comment by fichl** [comment]
@d3NNEb I cloned my fork and replaced your 4 files.
if i try to build your repo i get an error... 
Screenshot_248

**Comment by d3NNEb** [comment]
> @d3NNEb I cloned my fork and replaced your 4 files, downloading the zip file on your github. if i try to build your repo i get an error... Screenshot_248

if you could check-in / commit your current repo that is working (to your main or one of your branches) i can have a look and get this resolved

**Comment by fichl** [comment]
@d3NNEb if i put the nam files and the ir files in the same folder i get the same behaviour as in your video when closing and reopening nam window. if nam and ir files are in different folders, only the last loaded one will show the arrows.
Loading a reaper project is working like in your video unless you worked on another project and selected nams and or irs from different folders. It then shows the arrows only on either models or ir and crashes if you click on it.
when loading a saved project in cakewalk or element the arrows dont show at all.

**Pull request closed without merging**
